ARG version
FROM almalinux:${version}:-8}
ARG COURSE="Docker" \
TRAINER="Nagaraju" \
DURATION="10HRS" \
AUTHOR="nagarajupatnam"
RUN echo "Trainer is: ${TRAINER}, version is: ${version}"
CMD [ "sleep","200" ]